version: "3.9"
services:
  backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "777:777"
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "pi"
      POSTGRES_USER: "pi"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"